# Generated by Django 2.0.6 on 2020-03-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzg_houtaiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('times', models.CharField(max_length=20)),
                ('status', models.SmallIntegerField()),
                ('address', models.CharField(max_length=20)),
            ],
        ),
    ]
